[package]
name = "scheme-vm"
version = "0.1.0"
authors = ["Tim Morgan <tim@timmorgan.org>"]
build = "build.rs"

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.x"
ruby-sys = "0.2.20"

[build-dependencies]
peg = { git = "https://github.com/kevinmehall/rust-peg", branch = "master" }
