[package]
name = "scheme-vm"
version = "0.1.0"
authors = ["Tim Morgan <tim@timmorgan.org>"]

[lib]
crate-type = ["dylib"]

[dependencies]
libc = "0.2.37"
ruby-sys = "0.3.0"
lazy_static = "1.0.0"
pest = "^1.0"
pest_derive = "^1.0"
